name: Update APL

on:
  push:
    paths:
      - 'balance.txt'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: actions/checkout@v2
      - name: checkout simc
        uses: actions/checkout@v2
        with:
          repository: gastank/simc
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: './simc'
      - name: generate APL
        run: python generate_apl.py "./simc"
      - name: commmit APL
        run: |
          cd simc
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          git add .
          echo "[Balance] Update APL" > commit_msg
          echo >> commit_msg
          git log -1 --pretty=format:%B >> commit_msg
          git commit -F commit_msg
          rm commit_msg
          git push
